version: '3.8'

services:
  web:
    build:
      context: .
      target: dev
    command: python /app/src/django_import_manager/manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/app/
    ports:
      - 8000:8000
    env_file:
      - .env.dev
    depends_on:
      - db
  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=dim_dev_user
      - POSTGRES_PASSWORD=dim_dev_password
      - POSTGRES_DB=dim_dev_database
volumes:
  postgres_data: