version: '3.8'

services:
  web:
    build:
      context: .
      target: prod
    command: gunicorn django_import_manager.wsgi:application --bind 0.0.0.0:8000 --reload
    volumes:
      - static_volume:/app/staticfiles
    expose:
      - 8000
    env_file: .env.prod
    depends_on:
      - db
  nginx:
    build: ./nginx
    ports:
      - 1337:80
    volumes:
      - static_volume:/app/staticfiles
    depends_on:
      - web
  db:
    image: postgres:16
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data/
    env_file: .env.prod.db
volumes:
  postgres_data_prod:
  static_volume: